# Friday Sept 11: Sept What is a population?

Submit your answers to the Questions to Brightspace.

## To hand-in

1. Give a definition of a population from a textbook or peer-reviewed publication. Provide the citation.

1. Write 1 paragraph describing why the definition of a population matters?

1. Find a peer-reviewed paper where a population is studied. Write 1 paragraph discussing how a population is defined in the study.

## Resources

Vandermeer, J.H., Goldberg, D.E., 2013. Population Ecology: First Principles (Second Edition). Princeton University Press, Princeton, United States. [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=1205619)

The Princeton Guide to Ecology, edited by Simon A. Levin, et al., Princeton University Press, 2009. ProQuest Ebook Central, [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=557123)

Gunn, A., Russell, D. and Eamer, J. 2011. Northern caribou population trends in Canada. Canadian Biodiversity: Ecosystem Status and Trends 2010, Technical Thematic Report No. 10. Canadian Councils of Resource Ministers. Ottawa, ON. iv + 71 p. [Link](https://biodivcanada.chm-cbd.net/ecosystem-status-trends-2010/technical-report-10)

Sacchi, R., Gentilli, A., Razzetti, E., Barbieri, F., 2002. Effects of building features on density and flock distribution of feral pigeons Columba livia var. domestica in an urban environment. Can. J. Zool. 80, 48-54. [Link](https://doi.org/10.1139/z01-202)
