# Fri Oct 23: Stage-structured population dynamics

Some great visuals [here](https://twitter.com/seb_schreiber/status/1318574271854116866) from Dr. Sebastian Schreiber.

## Required Reading
Vandermeer, J.H., Goldberg, D.E., 2013. Population Ecology: First Principles (Second Edition). Princeton University Press, Princeton, United States. p39-40. [Link](https://ebookcentral-proquest-com.qe2a-proxy.mun.ca/lib/mun/detail.action?docID=1205619)

## Questions
1. Consider the projection matrix of the age-structured model from the previous class:
\begin{equation}
\left[
\begin{array}{cc}
0 & 2\\
0.5 & 0\\
\end{array}
\right]
\end{equation}
What are the special characteristics of the projection matrix for an age-structured population model (Leslie-Lewis matrix), that don't necessarily occur for a stage-structured population model (Leftkovitch matrix)? [1 mark]

2. Which elements of the Leftkovitch matrix may be larger than 1? Note that elements of the matrix occurring in a horizontal line are called rows, and elements occurring in a vertical line are called columns. [1 mark]

3. Complete Exercise 2.15 on p40 of Vandermeer and Goldberg (2013) [3 marks]. Note, where $\mathbb{P}$ is a Leftkovitch matrix, the element $p_{ij}$ is the contribution _from_ individuals in stage $j$ at time $t$, _to_ stage $i$ at time $t+1$, 

\begin{equation}
\mathbb{P} = 
\left[
\begin{array}{ccccc}
p_{11} & p_{12} & \dots & \dots & p_{1n} \\
p_{21} & p_{22} & \dots & \dots & p_{2n} \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
p_{n1} & \dots & \dots & \dots & p_{nn} \\
\end{array}
\right].
\end{equation}

