--- 
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
  bookdown::pdf_book:
    keep_tex: yes
documentclass: book
bibliography: [references.bib]
biblio-style: apalike
link-citations: false 
github-repo: https://github.com/ahurford/BIOL-3295-Fall-2020
---

# Thurs Sept 10: Syllabus
 
## Instructor Information

Instructor: Dr. Amy Hurford\
Office: Teaching remotely\
Email: ahurford@mun.ca\
I will try to reply to emails within 24 hours (excluding weekends and holidays). Outside of work hours, I am frequently unable to reply. I am always available during the lecture times. Please email to request a meeting for a different time.

## Course Information	
TR 12.00-12.50pm\
F 1-1.50pm\
WebEx links appear in the course materials on each relevant day\

Course description: Population and Evolutionary Ecology is an introduction to the theory and principles of evolutionary ecology and population dynamics. Pre-requisites: BIOL 2600; at least one of BIOL 2010, 2122 or 2210.\
	
Course format:\
The course has been re-designed for online delivery. Specifically, no exams that require invigilation are part of the grading scheme because these are challenging to invigilate remotely. Pre-recorded lectures limit my ability to interact with students. Therefore, I have elected to dedicate all lecture time to answering your questions. For each day of 'lecture' there is a list of questions you are required to answer and hand-in, ideally before the next class, but you have up to a week to submit your answers. There is also list of readings, that if completed, will allow you to answer the questions. Prior to 'lectures' you should complete the required readings, and I can most effectively help you if you have read over the questions ahead of time.\

Course expectations: Any students that are disruptive, violating university policies, or acting in a potentially unsafe way will be warned and asked to leave.\
	    
## Learning goals
I consider your completed assignments to be a portfolio of your knowledge in population and evolutionary ecology. You will also get some exposure to coding in `R`. It takes a while to become proficient in a programming language, but all the time you spend coding helps you towards becoming proficient. Some students may enjoy this aspect of the course and subsequently continue to build their programming abilities. The content emphasizes a deeper understanding of fewer concepts, and building your ability to learn more on your own.

## Required Text and Resources
The course materials are all (here)[].


Late assignments, labs, and missed midterms, and final exams will be accommodated as described by University Regulation 6.7.3 and 6.7.5 (see https://www.mun.ca/regoff/calendar/sectionNo=REGS-0474 for Regulations). The Final exam will cover all Lecture material and readings, but not Labs. Specific regulations governing final examinations are described by University Regulation 6.8. Lecture participation is highly recommended and practice problems completed during lectures may appear on Assignments.

Additional Policies
Accommodation of students with disabilities
Memorial University of Newfoundland is committed to supporting inclusive education based on the principles of equity, accessibility and collaboration. Accommodations are provided within the scope of the University Policies for the Accommodations for Students with Disabilities (www.mun.ca/policy/site/policy.php?id=239). Students who may need an academic accommodation are asked to initiate the request with the Glenn Roy Blundon Centre at the earliest opportunity (www.mun.ca/blundon). 

Academic misconduct
Students are expected to adhere to those principles, which constitute proper academic conduct. A student has the responsibility to know which actions, as described under Academic Offences in the University Regulations, could be construed as dishonest or improper. Students found guilty of an academic offence may be subject to a number of penalties commensurate with the offence including reprimand, reduction of grade, probation, suspension or expulsion from the University. For more information regarding this policy, students should refer to University Regulation 6.12. 

Equity and Diversity
A safe learning environment will be provided for all students regardless of race, colour, nationality, ethnic origin, social origin, religious creed, religion, age, disability, disfigurement, sex (including pregnancy), sexual orientation, gender identity, gender expression, marital status, family status, source of income or political opinion.

You should not photograph or record myself, teaching assistants, or other students in the class without first obtaining permission. Accommodation will be made for students with special needs.

The sound should be turned off on phones and computers during class.

Additional Supports
Resources for additional support can be found at:
•	www.mun.ca/currentstudents/student/
•	https://munsu.ca/resource-centres/



The last day to drop the course without academic prejudice is Wednesday Nov. 4.

## Grading

- 27 assignments - 50%
- Midterm - 15%
- Final Project - 35%

## Handing in your work

### Making figures to hand-in {#figures}
The graphs you hand in need to have descriptive axeses and a figure caption. You may put these elements together using a word processing software such as _Microsoft Word_.

### Writing R scripts to hand-in {#RScript}
To write your own R scripts follow the guidelines described in Chapter 7 [Best Practices](https://ahurford.github.io/quant-guide-all-courses/style.html) of _Quantitative training in Biology_. If you are asked to hand in your R script this means you need to submit an `.R` file to your dropbox on brightspace.

